### ISSUE TITLE
F0009 brexx recursively executes files that contain a bif identical to filename

### ISSUE THREAD

**Issue by rvjansen** [adesutherland/CMS-370-BREXX#11]
if we call x2d in a file called x2d.exec, brexx mixes up the search order and recursively starts the x2d.exec file, until resources are exhausted

**Comment by adesutherland** [comment]
Being working in feature/f0009

**Comment by adesutherland** [comment]
Initial Hotfix has been checked in. I am not certain if this should be pushed into live.

The way BREXX handles calls to external REXX programs is:
- When launching a program the program name is marked as a label 
  (Hotfix - check label and change type to EXTERNAL or BUILTIN)
- The single pass compiler will try and matchup calls to labels
- The interpreter then knows what do do when it gets a call
- Unmatched Calls trigger the **Interpreter** to try and load a REXX program. This is then compiled within the same context of the main program. This predicted the defect where a program can call a label in a second program (See code below).
- If a REXX program does not exist an external program is called (this is not implemented in CMS BREXX)
- Implementation of this type pf call - "func"() - is incomplete

The hot fix shows the problem - quite hard to maintain because the logic is not transparent and feels "organic", the hot fix just adds to this. Also separation of programs in the interpreter is not perfect.

TEST1 EXEC

    /* TEST1 */                 
    SAY TEST1            
    SAY TEST2("HELLO") /* This loads tests2 */   
    CALL TEST2BAD        /* And now this label is visible! */
    RETURN 0             

TEST2 EXEC

    /* TEST2 */                        
    PARSE ARG A                  
    SAY TEST2                    
    SAY A                        
    RETURN 1                     
                             
    TEST2BAD: PROCEDURE          
      SAY TEST2BAD                 
    RETURN

**Comment by adesutherland** [comment]
Fixed - new issue opened for remaining issue
